routes/web.php
<?php

use App\Exports\generarCaracterizacion;
use App\Exports\IndicadorExport;
use App\Exports\MacroprocesoExport;
use App\Exports\Reportes\PorTipoExport;
use App\Exports\Reportes\PorProcesosExport;
use App\Exports\Reportes\PorOrganicasExport;
use App\Exports\Reportes\IndicadoresExport;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AppsController;
use App\Http\Controllers\UserInterfaceController;
use App\Http\Controllers\CardsController;
use App\Http\Controllers\ComponentsController;
use App\Http\Controllers\ExtensionController;
use App\Http\Controllers\PageLayoutController;
use App\Http\Controllers\FormsController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\MiscellaneousController;
use App\Http\Controllers\AuthenticationController;
use App\Http\Controllers\ChartsController;
use App\Http\Controllers\ExportsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ReportesController;
/*Controladores de tablas*/
use App\Http\Controllers\sgc\ActividadController;
use App\Http\Controllers\sgc\AnioController;
use App\Http\Controllers\sgc\ArchivoController;
use App\Http\Controllers\sgc\AreaController;
use App\Http\Controllers\sgc\CargoController;
use App\Http\Controllers\sgc\DetalleController;
use App\Http\Controllers\sgc\DocumentodetalleController;
use App\Http\Controllers\sgc\DocumentoController;
use App\Http\Controllers\sgc\EscalaController;
use App\Http\Controllers\sgc\EvaluacionController;
use App\Http\Controllers\sgc\EvidenciaController;
use App\Http\Controllers\sgc\IndicadorController;
use App\Http\Controllers\sgc\InteresadoController;
use App\Http\Controllers\sgc\MacroprocesoController;
use App\Http\Controllers\sgc\MecanismoController;
use App\Http\Controllers\sgc\MedicionController;
use App\Http\Controllers\sgc\MicroprocesoController;
use App\Http\Controllers\sgc\ParametroController;
use App\Http\Controllers\sgc\PersonaController;
use App\Http\Controllers\sgc\ProcesomecanismoController;
use App\Http\Controllers\sgc\ProcesoController;
use App\Http\Controllers\sgc\RecursoController;
use App\Http\Controllers\sgc\RequisitoController;
use App\Http\Controllers\sgc\RestriccionController;
use App\Http\Controllers\sgc\ResultadodetalleController;
use App\Http\Controllers\sgc\ResultadoController;
use App\Http\Controllers\sgc\RoleController;
use App\Http\Controllers\sgc\SubprocesoController;
use App\Http\Controllers\sgc\SuministrainfoController;
use App\Http\Controllers\sgc\TerminoController;
use App\Http\Controllers\sgc\TrabajadorController;
use App\Http\Controllers\sgc\VersionController;


use App\Http\livewire\ActividadComponent;
use App\Http\livewire\AnioComponent;
use App\Http\livewire\AreaComponent;
use App\Http\livewire\CargoComponent;
use App\Http\livewire\DetalleComponent;
use App\Http\livewire\DocumentoComponent;
use App\Http\livewire\TrabajadorComponent;

use App\Http\livewire\EscalaComponent;
use App\Http\livewire\EvaluacionComponent;
use App\Http\livewire\ResultadoComponent;
use App\Http\livewire\SuministroComponent;
use App\Http\livewire\EvidenciasComponent;
use App\Models\Indicador;
use App\Models\Subproceso;

// Main Page Route
Route::get('/', function () {
    return redirect()->route('login');
});

//Link personalizados
Route::get('/home', [HomeController::class, 'index'])->name('home-index');
Route::get('/cambiarmirol/{id}', function ($id) {
    cambiarRol($id);
});

Route::middleware(['auth','revisa_asignacion'])->group(function () {
    Route::resource('archivos', ArchivoController::class);
    // Route::resource('actividads', ActividadController::class);
    // Route::resource('anios', AnioController::class);
    // Route::resource('areas', AreaController::class);
    // Route::resource('cargos', CargoController::class);
    // Route::resource('detalles', DetalleController::class);
    Route::resource('documentos', DocumentoController::class);
    // Route::resource('escalas', EscalaController::class);
    // Route::resource('evaluacions', EvaluacionController::class);
    //Route::resource('evidencias', EvidenciaController::class);
    Route::resource('evidencias', EvidenciasComponent::class);
    // Route::view('indicadores', 'livewire.indicadors.index')->name('indicadors.index');
    Route::get('indicadores', [IndicadorController::class, 'index'])->name('indicadors.index');
    Route::get('indicadores/audit', [IndicadorController::class, 'audit'])->name('indicadors.audit');
    //Route::view('interesados', 'livewire.interesados.index')->name('interesados.index');
    Route::resource('interesados', InteresadoController::class);
    Route::resource('macroprocesos', MacroprocesoController::class);
    Route::get('macroprocesos/{macroproceso}/caracterizacion', [MacroprocesoController::class, 'caracterizacion'])->name('macroprocesos.caracterizacion');
    //Route::get('macroprocesos/{macroproceso}/ficha', [\App\Http\Livewire\Indicadors::class, 'ficha'])->name('macroprocesos.ficha');
    Route::get('macroprocesos/{macroproceso}/ficha', [\App\Http\Livewire\FichaIndicador::class, 'ficha'])->name('macroprocesos.ficha');
    Route::get('macroprocesos/{indicador}/{anio}/showFicha', [\App\Http\Livewire\FichaIndicador::class, 'showFicha'])->name('show.ficha');
    Route::view('macroprocesos', 'livewire.macroprocesos.index')->name('macroprocesos.index');
    Route::view('mecanismos', 'livewire.mecanismos.index')->name('mecanismos.index');
    Route::view('mediciones', 'livewire.medicions.index');
    // Route::view('microprocesos', 'livewire.microprocesos.index')->name('microprocesos.index');
    Route::resource('microprocesos', MicroprocesoController::class);
    Route::view('parametros', 'livewire.parametros.index')->name('parametros.index');
    Route::resource('personas', PersonaController::class);
    Route::view('usuarios', 'livewire.users.index')->name('users.index');
    Route::view('procesomecanismos', 'livewire.procesomecanismos.index')->name('procesomecanismos.index');
    Route::resource('procesos', ProcesoController::class);
    Route::get('procesos/{proceso}/caracterizacion', [ProcesoController::class, 'caracterizacion'])->name('procesos.caracterizacion');
    // Route::view('procesos', 'livewire.procesos.index')->name('procesos.index');
    Route::resource('recursos', RecursoController::class);
    // Route::view('recursos', 'livewire.recursos.index')->name('recursos.index');
    Route::resource('requisitos', RequisitoController::class);
    Route::resource('restricciones', RestriccionController::class);
    // Route::view('restricciones', 'livewire.restriccions.index');
    Route::resource('resultadodetalles', ResultadodetalleController::class);
    Route::resource('resultados', ResultadoController::class);
    //Route::view('resultados', 'livewire.resultados.index')->name('resultados.index');
    Route::resource('roles', RoleController::class);
    //Route::view('roles', 'livewire.roles.index')->name('roles.index');
    Route::resource('subprocesos', SubprocesoController::class);
    Route::get('subprocesos/{subproceso}/caracterizacion', [SubprocesoController::class, 'caracterizacion'])->name('subprocesos.caracterizacion');
    Route::resource('suministrainfos', SuministrainfoController::class);
    Route::resource('terminos', TerminoController::class);
    // Route::view('terminos', 'livewire.terminos.index');
    Route::resource('trabajadores', TrabajadorController::class);

    Route::resource('versiones', VersionController::class);
    Route::view('versiones', 'livewire.versions.index');
    Route::view('vinculaciones', 'livewire.vinculacions.index')->name('vinculacions.index');

    Route::resource('macroprocesos', MacroprocesoController::class);

    Route::resource('actividads', ActividadComponent::class);
    //Route::resource('anios', AnioComponent::class);
    Route::resource('anios', AnioController::class);
    //Route::resource('areas', AreaComponent::class);
    Route::resource('areas', AreaController::class);
    // Route::resource('cargos', CargoComponent::class);
    Route::resource('cargos', CargoController::class);
    Route::resource('detalles', DetalleComponent::class);
    // Route::resource('documentos', DocumentoComponent::class);
    // Route::resource('trabajadores', TrabajadorComponent::class);
    Route::resource('trabajadores', TrabajadorController::class);
    // Route::resource('documentosDetalles', ShowDocumentodetalles::class);
    Route::resource('escalas', EscalaComponent::class);
    Route::resource('evaluaciones', EvaluacionComponent::class);
    //Route::resource('evaluaciones', EvaluacionComponent::class);
    // Route::resource('resultados', ResultadoComponent::class);
    Route::resource('suministros', SuministroComponent::class);

    Route::get('mfichacaracterizacion', [MacroprocesoController::class, 'fichaCaracterizacion'])->name('ficha-caracterizacion');
    //la nínea siguiente no sirve
    Route::get('fichacaracterizacion', [MacroprocesoController::class, 'fichaCaracterizacionProcesos'])->name('ficha-caracterizacion-procesos');
    Route::get('fichaindicador/{id}', [MacroprocesoController::class, 'fichaIndicador'])->name('ficha.indicador');

    Route::get('dashboard', [HomeController::class, 'dashboard'])->name('dashboard.index');
    Route::get('caracterizacion', [HomeController::class, 'caracterizacion'])->name('caracterizacion.index');
    Route::get('manuales/proceso', [HomeController::class, 'mProceso'])->name('manuales.proceso');

    Route::get('manuales/macroproceso/{macroproceso}', [HomeController::class, 'mMacroProcesoVer'])->name('manuales.macroproceso.view');
    Route::get('manuales/proceso/{proceso}', [HomeController::class, 'mProcesoVer'])->name('manuales.proceso.view');

    Route::get('manuales/software', [HomeController::class, 'mSoftware'])->name('manuales.software');

resources/views/content/layouts/home.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Inicio')

@section('vendor-style')
  {{-- vendor css files --}}
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/charts/apexcharts.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/toastr.min.css')) }}">
@endsection
@section('page-style')
  {{-- Page css files --}}
  <link rel="stylesheet" href="{{ asset(mix('css/base/pages/dashboard-ecommerce.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/charts/chart-apex.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('css/base/plugins/extensions/ext-component-toastr.css')) }}">
  <style>
    .disabled {
      --bs-bg-opacity: 1;
      background-color: rgba(155, 155, 155,0.2) !important;
    }
  </style>
@endsection

@section('content')
<!-- Dashboard Ecommerce Starts -->
<section id="home">

  <div class="row match-height">
    <!-- Browser States Card -->
    <div class="col-lg-2 col-md-6 col-12">
      <div class="card">
        <div class="card-body text-center" style="writing-mode: vertical-rl; transform: rotate(180deg);">
          <div class="border border-primary">
            <h4 class="card-title">NECESIDADES Y EXPECTATIVAS</h4>
            <h4 class="card-title">GRUPOS DE INTERÉS UNASAM</h4>
          </div>
          <svg viewBox="0 0 100 100"  xmlns="http://www.w3.org/2000/svg" height="60">
            <rect height="30" transform="translate(130 100) rotate(-180)" width="40" x="50" y="35"/>
            <polygon points="50 80 50 20 20 50 50 80"/>
          </svg>
        </div>
      </div>
    </div>
    <!--/ Browser States Card -->

    <!-- Goal Overview Card -->
    <div class="col-lg-8 col-md-6 col-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center pb-0">
          <h4 class="card-title">PROCESOS ESTRATÉGICOS</h4>
        </div>
        <div class="card-body p-2 m-2 border border-secundary">
            <div class="row">
              <div class="col-md-3">
                <a href="#" class="btn btn-outline-primary waves-effect d-flex bg-light disabled" style="height: 80px; align-items: center;">Gestión de la Dirección</a>
              </div>
              <div class="col-md-3">
                <a href="{{route('macroprocesos.show',2)}}" class="btn btn-outline-primary waves-effect d-flex" style="height: 80px; align-items: center;">Gestión de la Calidad</a>
              </div>
              <div class="col-md-3">
                <a href="#" class="btn btn-outline-primary waves-effect disabled">Gestión de La Comunicación y Relaciones Estratégicas</a>
              </div>
              <div class="col-md-3">
                <a href="#" class="btn btn-outline-primary waves-effect d-flex disabled" style="height: 80px; align-items: center;">Gestión del Servicio Educativo</a>
              </div>
            </div>
        </div>
        <div class="card-header d-flex justify-content-between align-items-center pb-0">
          <h4 class="card-title">PROCESOS MISIONALES</h4>
        </div>
        <div class="card-body p-2 m-2 border border-secundary">
          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-2">
              <a href="{{route('macroprocesos.show',7)}}" class="btn btn-outline-primary waves-effect d-flex justify-content-center align-items-center" style="height: 50px;">I+D+i </a>
            </div>
            <div class="col-md-1 justify-content-center" style="height: 50px; align-items: center;">
              <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                <rect height="30" transform="translate(100 100) rotate(-180)" width="30" x="35" y="35"/>
                <polygon points="40 80 40 20 10 50 40 80"/>
                <polygon points="60 80 60 20 90 50 60 80"/>
              </svg>
            </div>
            <div class="col-md-2">
              <a href="{{route('macroprocesos.show',8)}}" class="btn btn-outline-primary waves-effect d-flex justify-content-center align-items-center" style="height: 50px;">RSU</a>
            </div>
            <div class="col-md-4"></div>
          </div>
          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-2">
              <!-- <div class="d-flex justify-content-center" style="text-align: center; display: inline-block;"> -->
              <div class="d-flex justify-content-end" style="text-align: center; display: inline-block;">
                <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" style="transform: rotate(90deg);">
                  <rect height="30" transform="translate(100 100) rotate(-180)" width="30" x="35" y="35"/>
                  <polygon points="40 80 40 20 10 50 40 80"/>
                  <polygon points="60 80 60 20 90 50 60 80"/>
                </svg>
              </div>
            </div>
              <div class="col-md-1 d-none d-md-block"></div>
              <div class="col-md-2 d-none d-md-block">
                <div class="d-flex justify-content-start" style="text-align: center; display: inline-block;">
                  <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" style="transform: rotate(90deg);">
                    <rect height="30" transform="translate(100 100) rotate(-180)" width="30" x="35" y="35"/>
                    <polygon points="40 80 40 20 10 50 40 80"/>
                    <polygon points="60 80 60 20 90 50 60 80"/>
                  </svg>
                </div>
              </div>
            <!-- </div> -->
            <div class="col-md-4"></div>
          </div>
          <div class="row">
            <div class="col-md-1"></div>            
            <div class="col-md-2">
              <a href="#" class="btn btn-outline-primary waves-effect d-flex justify-content-center align-items-center disabled" style="height: 50px;">Admisión</a>
            </div>
            <div class="col-md-1">
              <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                <rect height="30" width="30" x="20" y="35"/>
                <polygon points="50 80 50 20 80 50 50 80"/>
              </svg>
            </div>
            <div class="col-md-3">
              <a href="{{route('macroprocesos.show',6)}}" class="btn btn-outline-primary waves-effect d-flex justify-content-center align-items-center" style="height: 50px;">Formación Profesional</a>
            </div>
            <div class="col-md-1 ">
              <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                <rect height="30" width="30" x="20" y="35"/>
                <polygon points="50 80 50 20 80 50 50 80"/>
              </svg>
            </div>
            <div class="col-md-3">
              <a href="#" class="btn btn-outline-primary waves-effect d-flex justify-content-center align-items-center disabled" style="height: 50px;">Graduación Titulación</a>
            </div>
            <div class="col-md-1"></div>
          </div>
          <!-- <div class="row">
            <div class="col-md-12 justify-content-center" style="text-align: center; margin-left: -45px;">
              <a href="{{route('macroprocesos.show',7)}}" class="btn btn-outline-primary waves-effect">I+D+i </a>
              <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                <rect height="30" transform="translate(100 100) rotate(-180)" width="30" x="35" y="35"/>
                <polygon points="40 80 40 20 10 50 40 80"/>
                <polygon points="60 80 60 20 90 50 60 80"/>
              </svg>
              <a href="{{route('macroprocesos.show',8)}}" class="btn btn-outline-primary waves-effect">RSU</a>
            </div>
          </div>
          <div class="row">
            <div class="d-flex justify-content-center" style="text-align: center; display: inline-block;">
                <div style="margin-left: -90px; margin-right: 80px;">
                  <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" style="transform: rotate(90deg);">
                    <rect height="30" transform="translate(100 100) rotate(-180)" width="30" x="35" y="35"/>
                    <polygon points="40 80 40 20 10 50 40 80"/>
                    <polygon points="60 80 60 20 90 50 60 80"/>
                  </svg>
                </div>
                <div>
                  <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" style="transform: rotate(90deg);">
                    <rect height="30" transform="translate(100 100) rotate(-180)" width="30" x="35" y="35"/>
                    <polygon points="40 80 40 20 10 50 40 80"/>
                    <polygon points="60 80 60 20 90 50 60 80"/>
                  </svg>
                </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 justify-content-center" style="text-align: center;">
              <a href="#" class="btn btn-outline-primary waves-effect">Admisión</a>
              <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                <rect height="30" width="30" x="20" y="35"/>
                <polygon points="50 80 50 20 80 50 50 80"/>
              </svg>
              <a href="{{route('macroprocesos.show',6)}}" class="btn btn-outline-primary waves-effect">Formación Profesional</a>
              <svg height="38" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                <rect height="30" width="30" x="20" y="35"/>
                <polygon points="50 80 50 20 80 50 50 80"/>
              </svg>
              <a href="#" class="btn btn-outline-primary waves-effect">Graduación Titulación</a>
            </div>
          </div> -->

        </div>

        <div class="card-body p-2 m-2 border border-secundary">
          <div class="row">
            <div class="col-md-2 justify-content-center" style="text-align: center;">
              <a href="#" class="btn btn-outline-primary waves-effect d-flex disabled px-50" style="height: 105px; align-items: center;">Bienestar Universitario</a>
            </div>
            <div class="col-md-8 justify-content-center border border-primary " style="text-align: center;">
              <div class="row">
                <div class="text-center" style="margin-top: 5px;">
                  <h5>Recursos de Apoyo</h5>
                </div>
              </div>
              <div class="row" style="margin-bottom: 6px;">
                  <div class="col-md-4">
                    <a href="#" class="btn btn-outline-primary waves-effect d-flex disabled" style="height: 66px; align-items: center;">
                      Infraestructura y equipamiento
                    </a>
                  </div>
                  <div class="col-md-4">
                    <a href="#" class="btn btn-outline-primary waves-effect d-flex disabled">
                      Tecnología de la información y comunicación
                    </a>
                  </div>
                  <div class="col-md-4">
                    <a href="#" class="btn btn-outline-primary waves-effect d-flex disabled" style="height: 66px; align-items: center;">
                      Biblioteca especializada
                    </a>
                  </div>
                  {{-- <div class="col-md-4 text-center">
                    <a href="#" class="btn btn-outline-primary waves-effect d-flex text-center" style="height: 66px; align-items: center;">Biblioteca</a>
                  </div> --}}
              </div>
            </div>
            <div class="col-md-2 justify-content-center" style="text-align: center;">
              <a href="#" class="btn btn-outline-primary waves-effect d-flex disabled px-50" style="height: 105px; align-items: center;">Recursos Humanos</a>
            </div>
          </div>
        </div>        
        <div class="card-header d-flex justify-content-between align-items-center pt-0">
          <h4 class="card-title">PROCESOS DE SOPORTE</h4>
        </div>
      </div>
    </div>

    <div class="col-lg-2 col-md-6 col-12">
      <div class="card card-transaction">
        <div class="card-body text-center " style="writing-mode: vertical-rl; transform: rotate(180deg);">
          <svg viewBox="0 0 100 100"  xmlns="http://www.w3.org/2000/svg" height="60">
            <rect height="30" transform="translate(130 100) rotate(-180)" width="40" x="50" y="35"/>
            <polygon points="50 80 50 20 20 50 50 80"/>
          </svg>
          <div class="border border-primary">
            <h4 class="card-title">SATISFACCIÓN DE NECESIDADES Y EXPECTATIVAS</h4>
            <h4 class="card-title">GRUPOS DE INTERÉS UNASAM</h4>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>
<!-- Dashboard Ecommerce ends -->
@endsection

@section('vendor-script')
  {{-- vendor files --}}
  <script src="{{ asset(mix('vendors/js/charts/apexcharts.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/extensions/toastr.min.js')) }}"></script>
  @endsection
@section('page-script')
  <script>
    $user = @js(Auth::user()->name);
    var isRtl = $('html').attr('data-textdirection') === 'rtl';
    /*if ($user) {
      toastr['success'](
        'Has iniciado sesión con éxito al SGC. ¡Ahora puedes empezar a explorar!',
        '👋 ¡Bienvenido '+$user+'!',
        {
            closeButton: true,
            tapToDismiss: false,
            closeDuration: 2000,
            rtl: isRtl
        }
      );
    }*/
  </script>
@endsection